### ISSUE TITLE
Wiki Horizontal Scaling

### ISSUE THREAD

**Issue by HugTeddy** [galahad-creative/idle-mmo-wiki#2]
Wiki doesn't seem to scale horizontally to larger screens on desktop. This also occurs on mobile devices accessing through web browsers. 

![image](https://github.com/galahad-creative/idle-mmo-wiki/assets/62405530/6ba1c11f-2578-4670-81e5-d8186818c88b)

**Comment by GalahadXVI** [comment]
Hey! This is intentional. It is designed to be narrow and incredibly simple to use. Supporting widescreen browsers is not something we are considering right now. Thanks.
